packages:
  - playground
  - 'packages/*'
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@types/node': ^22.19.11
  '@unocss/eslint-config': ^66.6.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vitest/coverage-c8': ^0.33.0
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.2.1
  bumpp: ^10.4.1
  eslint: ^9.23.0
  eslint-plugin-format: ^1.4.0
  jsdom: ^28.0.0
  lint-staged: ^16.2.7
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.3
  unocss: ^66.6.0
  vite: ^7.3.1
  vitest: ^4.0.18
  vue: ^3.5.28
  vue-tsc: ^3.2.4
